services:
  postgres:
    image: postgres:18-alpine
    container_name: "payzeph_postgres"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payzeph_network

  redis:
    image: redis:7-alpine
    container_name: "payzeph_redis"
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - payzeph_network

volumes:
  postgres_data:
  redis_data:

networks:
  payzeph_network:
    driver: bridge
